; mart types (see engine/items/mart.asm)
	const_def
	const MARTTYPE_STANDARD
	const MARTTYPE_BITTER
	const MARTTYPE_BARGAIN
	const MARTTYPE_PHARMACY
	const MARTTYPE_ROOFTOP

; Marts indexes (see data/items/marts.asm)
	const_def
	const MART_CHERRYGROVE_BEFORE_DEX
	const MART_MAHOGANY_ROCKET
	const MART_MAIL
	const MART_EVO_ITEMS
	const MART_VITAMINS
	const MART_BATTLE_ITEMS
	const MART_GOLDENROD_TMS
	const MART_CELADON_TMS
	const MART_MT_MOON
	const MART_UNDERGROUND
	const MART_GENERAL_0_BADGES
	const MART_GENERAL_2_BADGES
	const MART_GENERAL_4_BADGES
	const MART_GENERAL_6_BADGES
	const MART_GENERAL_8_BADGES
DEF NUM_MARTS EQU const_value
